# Generated by Django 5.2.3 on 2025-06-11 20:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('in_use', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
