# Generated by Django 5.2.3 on 2025-06-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_product_id_alter_testclass_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestClass',
        ),
    ]
