# Generated by Django 5.2.3 on 2025-06-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=6),
            preserve_default=False,
        ),
    ]
